dom 11 jan 2026 21:45:31 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/usr/local/bin/void-xrandr b/usr/local/bin/void-xrandr
--- a/usr/local/bin/void-xrandr
+++ b/usr/local/bin/void-xrandr
@@ -1,12 +1,13 @@
 #!/usr/bin/env bash
-#shellcheck disable=SC2145,SC2001,SC2188,SC2015,SC2155,SC2317,SC2320,SC2291,SC2034,SC2120,SC2086,SC2319
-#shellcheck disable=SC2016,SC2154,SC2207,SC2166,SC2128,SC2059,SC2140,SC2031,SC2030,SC2036,SC2119,SC2027
-
-#  void-install
-#  Created: 2022/12/24
-#  Altered: 2024/03/08
+# -*- coding: utf-8 -*-
+# shellcheck shell=bash disable=SC1091,SC2039,SC2166
 #
-#  Copyright (c) 2022-2024, Vilmar Catafesta <vcatafesta@gmail.com>
+#  chili-xrandr - Wrapper config resolution using xrandr, umc e cvt
+#  Created: 2019/07/15 - 23:02
+#  Altered: 2025/02/08 - 10:13
+#  Updated: 2025/02/08 - 10:36
+#
+#  Copyright (c) 2019-2025, Vilmar Catafesta <vcatafesta@gmail.com>
 #  All rights reserved.
 #
 #  Redistribution and use in source and binary forms, with or without
@@ -18,7 +19,7 @@
 #     notice, this list of conditions and the following disclaimer in the
 #     documentation and/or other materials provided with the distribution.
 #
-#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
+#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR AS IS'' AND ANY EXPRESS OR
 #  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 #  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 #  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
@@ -28,24 +29,127 @@
 #  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 #  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 #  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-############################################################################
+##############################################################################
 #export LANGUAGE=pt_BR
 export TEXTDOMAINDIR=/usr/share/locale
-export TEXTDOMAIN=void-xrandr
+export TEXTDOMAIN=chili-xrandr
+
+# Definir a variável de controle para restaurar a formatação original
+reset=$(tput sgr0)
+
+# Definir os estilos de texto como variáveis
+bold=$(tput bold)
+underline=$(tput smul)   # Início do sublinhado
+nounderline=$(tput rmul) # Fim do sublinhado
+reverse=$(tput rev)      # Inverte as cores de fundo e texto
+
+# Definir as cores ANSI como variáveis
+black=$(tput bold)$(tput setaf 0)
+red=$(tput bold)$(tput setaf 196)
+green=$(tput bold)$(tput setaf 2)
+yellow=$(tput bold)$(tput setaf 3)
+blue=$(tput setaf 4)
+pink=$(tput setaf 5)
+magenta=$(tput setaf 5)
+cyan=$(tput setaf 6)
+white=$(tput setaf 7)
+gray=$(tput setaf 8)
+orange=$(tput setaf 202)
+purple=$(tput setaf 125)
+violet=$(tput setaf 61)
+light_red=$(tput setaf 9)
+light_green=$(tput setaf 10)
+light_yellow=$(tput setaf 11)
+light_blue=$(tput setaf 12)
+light_magenta=$(tput setaf 13)
+light_cyan=$(tput setaf 14)
+bright_white=$(tput setaf 15)
 
 #debug
-export PS4='${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset} '
+export PS4='${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset}'
 #set -x
 #set -e
 shopt -s extglob
 
+# NOTES:
+## Universal Modeline Calculator (UMC) - Calculadora de Modelines para Xorg
+## https://github.com/chililinux/umc
+## https://sourceforge.net/projects/umc/
+## https://sourceforge.net/projects/umc/files/umc/umc-0.2/umc-0.2.tar.gz/download
+
 #system
-readonly APP="${0##*/}"
-readonly _VERSION_='1.0.18-20240308'
-readonly distro=$(uname -n)
-readonly DEPENDENCIES=(xrandr cvt tput dialog awk grep sed gettext)
-readonly sep='\xe2\x94\x82'
-readonly ccabec="$APP v${_VERSION_} - https://github.com/voidlinux-br/void-install"
+declare APP="${0##*/}"
+declare APPDESC="$(gettext 'Wrapper config resolution using xrandr, umc e cvt')"
+declare _VERSION_="1.2.08-20250208"
+declare distro="$(uname -n)"
+declare DEPENDENCIES=(tput dialog awk grep sed xrandr cvt umc)
+declare sep='\xe2\x94\x82'
+declare dialogRcFile="$HOME/.dialogrc"
+declare ccabec="$APP - $_VERSION_ - $APPDESC"
+
+sh_create_dialogrc() {
+	cat >"$dialogRcFile" <<-DIALOG_EOF
+		screen_color = (white,black,off)
+		dialog_color = (white,black,off)
+		title_color = (cyan,black,on)
+		border_color = dialog_color
+		shadow_color = (black,black,on)
+		button_inactive_color = dialog_color
+		button_key_inactive_color = dialog_color
+		button_label_inactive_color = dialog_color
+		button_active_color = (white,cyan,on)
+		button_key_active_color = button_active_color
+		button_label_active_color = (black,cyan,on)
+		tag_key_selected_color = (white,cyan,on)
+		item_selected_color = tag_key_selected_color
+    form_text_color = (BLUE,black,ON)
+		form_item_readonly_color = (green,black,on)
+		itemhelp_color = (white,cyan,off)
+		inputbox_color = dialog_color
+		inputbox_border_color = dialog_color
+		searchbox_color = dialog_color
+		searchbox_title_color = title_color
+		searchbox_border_color = border_color
+		position_indicator_color = title_color
+		menubox_color = dialog_color
+		menubox_border_color = border_color
+		item_color = dialog_color
+		tag_color = title_color
+		tag_selected_color = button_label_active_color
+		tag_key_color = button_key_inactive_color
+		check_color = dialog_color
+		check_selected_color = button_active_color
+		uarrow_color = screen_color
+		darrow_color = screen_color
+		form_active_text_color = button_active_color
+		gauge_color = title_color
+		border2_color = dialog_color
+		searchbox_border2_color = dialog_color
+		menubox_border2_color = dialog_color
+		separate_widget = ''
+		tab_len = 0
+		visit_items = off
+		use_shadow = off
+		use_colors = on
+	DIALOG_EOF
+	export DIALOGRC="$dialogRcFile"
+}
+
+# Testa se o terminal suporta caracteres gráficos estendidos
+sh_ascii_lines() {
+	#Isso força o dialog a usar caracteres ASCII básicos para as bordas.
+	#if [[ "$LANG" =~ 'UTF-8' ]]; then
+	if [[ "$(printf '\u250C')" =~ "┌" ]]; then
+		export NCURSES_NO_UTF8_ACS=1 # Terminal suporta ACS
+	else
+		export NCURSES_NO_UTF8_ACS=0 # Terminal NÃO suporta ACS
+	fi
+}
+
+sh_setEnvironment() {
+   [[ ! -e "$dialogRcFile" ]] && sh_create_dialogrc
+   sh_ascii_lines
+}
 
 sh_setconf() {
 	COL_NC='\e[0m' # No Color
@@ -66,21 +170,21 @@ inkey() {
 
 sh_checkDependencies() {
 	local d
-	local errorFound=0
+	local errorFound=false
 	declare -a missing
 
 	for d in "${DEPENDENCIES[@]}"; do
-		[[ -n $(command -v "$d") ]] && { :; } || {
-			log_msg "$(gettext "ERRO: Não foi possível encontrar o comando") ${cyan}'$d'${reset}"
+		[[ -n $(command -v "$d") ]] && { log_msg "Check: ${cyan}$d"; } || {
+			log_msg "ERROR: Could not find command ${cyan}'$d'${reset}"
 			missing+=("$d")
-			errorFound=1
+			errorFound=true
 		}
 	done
-	if ((errorFound)); then
-		echo "${yellow}$(gettext "---------------IMPOSSÍVEL CONTINUAR---------------")"
-		echo "${red}$(gettext "Este script precisa dos comandos listados acima")"
-		echo "$(gettext "Instale-os e/ou certifique-se de que estejam em seu") \$PATH"
-		echo "${yellow}$(gettext "---------------IMPOSSÍVEL CONTINUAR---------------")"
+	if $errorFound; then
+		echo "${yellow}---------------IMPOSSIBLE TO CONTINUE---------------"
+		echo "${red}This script needs the commands listed above"
+		echo "Install them and/or make sure they are in your \$PATH"
+		echo "${yellow}---------------IMPOSSIBLE TO CONTINUE---------------"
 		die "Aborted!"
 	fi
 }
@@ -160,8 +264,13 @@ sh_getoutput() {
 
 	#	aOutput=('VGA-1' 'DVI-1' 'HDMI-1')
 	#	mapfile -t aOutput <<< "$(xrandr  | grep " connected " | awk '{ print$1 }')"	#conectado
-	mapfile -t aOutput <<<"$(xrandr | grep "connected " | awk '{ print$1 }')"  #todos
-	mapfile -t aConnect <<<"$(xrandr | grep "connected " | awk '{ print$2 }')" #todos
+  echo "$red"
+	if xrandr 1>/dev/null; then
+  	mapfile -t aOutput <<<"$(xrandr | grep "connected " | awk '{ print$1 }')"  #todos
+  	mapfile -t aConnect <<<"$(xrandr | grep "connected " | awk '{ print$2 }')" #todos
+  else
+    die "fatal"
+  fi
 
 	for x in "${aOutput[@]}"; do
 		arr[n++]="$x"
@@ -175,16 +284,14 @@ sh_getoutput() {
 			--colors \
 			--clear \
 			--backtitle "$ccabec" \
-			--title "$APP $(getttext "resolução")" \
-			--cancel-label "$(gettext "Cancelar")" \
-			--ok-label "$(gettext "Aceitar")" \
-			--menu "\n$(gettext "Escolha o dispositivo para configuração"):" \
+			--title "Menu VIDEO DEVICE" \
+			--menu '\nChoose device output for set:' \
 			0 0 0 \
 			"${arr[@]}")
 
 		nExit=$?
 		if ((nExit)); then
-			die "$(gettext "Cancelado!")"
+			die 'Cancelled!'
 		fi
 		break
 	done
@@ -200,8 +307,8 @@ sh_setrand() {
 	local x y
 
 	# 	aVmode=('1080' '1080' '1080')
-	aHmode=('2560 1080' '1920 1080' '1680 1080')
-	aRefresh=('33' '44' '50' '60' '75')
+	aHmode=('3840 2160' '2560 1080' '1920 1080' '1680 1080' '1366 768' '1024 768' '800 600')
+	aRefresh=('30' '33' '44' '50' '60' '75')
 
 	for x in "${aHmode[@]}"; do
 		for y in "${aRefresh[@]}"; do
@@ -216,15 +323,15 @@ sh_setrand() {
 			--colors \
 			--clear \
 			--backtitle "$ccabec" \
-			--title "$APP $(getttext "resolução")" \
-			--ok-label "$(gettext "Adicionar")" \
-			--cancel-label "$(gettext "Cancelar")" \
-			--menu "\n$(gettext "Escolha o dispositivo para configuração"):" \
+			--title "Menu CHOOSE RESOLUTION" \
+			--ok-label "Add" \
+			--extra-button --extra-label "Remove" \
+			--menu '\nChoose resolution for set:' \
 			0 0 0 \
 			"${arr[@]}")
 
 		nExit=$?
-		[[ "$nExit" -eq 1 ]] && die "$(gettext "Cancelado!")"
+		[[ "$nExit" -eq 1 ]] && die 'Cancelled!'
 		modeline=$(cvt $nchoice | grep Modeline | sed 's/Modeline //')
 		modeline="${modeline%%_*}-custom ${modeline#* }"
 		mode=$(awk '{print $1}' <<<"$modeline")
@@ -237,6 +344,7 @@ sh_setrand() {
 		0) #add
 			xrandr --verbose --newmode $modeline
 			xrandr --verbose --addmode $output $mode
+			xrandr --verbose --output $output --mode $mode
 			inkey 2
 			;;
 		3) # remove
@@ -247,8 +355,10 @@ sh_setrand() {
 	done
 }
 
+sh_setEnvironment
 sh_setconf
 sh_setvarcolors
 sh_checkDependencies
+#sh_setdevboy
 sh_getoutput
 sh_setrand
